name: Edit Internship
description: Edit an internship on our list
title: "Editing Internship"
labels: ["edit_internship"]
body:
  - type: markdown
    attributes:
      value: |
        ## Formulario para editar un Internship
        ¡Gracias por tomarte el tiempo de ayudarnos!
        > Asegúrate de hacer leído el `CONTRIBUTING.md` antes de enviar tus cambios
        Por favor únicamente llena **link, razón y cualquier otro campo que quieras cambiar**
        Puedes dejar los demás vacíos
  - type: input
    id: url
    attributes:
      label: Link a la publicación del Internship
      placeholder: ex. example.com/link/to/posting
    validations:
      required: true
  - type: input
    id: company_name
    attributes:
      label: Nombre de la compañía
      placeholder: ex. Google
    validations:
      required: false
  - type: input
    id: title
    attributes:
      label: Título del Internship
      placeholder: ex. ML Software Intern
    validations:
      required: false
  - type: input
    id: location
    attributes:
      label: Lugar
      description: |
        ¿Dónde está ubicado?
        Por favor separa los lugares con un *pipe* "|" si son varios lugares.
        Incluye *Remote* si la opción de hacerlo remoto está disponible.
      placeholder: ex. Ciudad de México, México | Tlaquepaque, Jalisco | Remoto
    validations:
      required: false
  - type: dropdown
    id: terms
    attributes:
      label: ¿En qué temporada es el internship?
      multiple: true
      options:
        - Winter 2024
        - Spring 2024
        - Summer 2024
        - Fall 2024
    validations:
      required: false
  - type: dropdown
    id: english
    attributes:
      label: ¿La posición necesita saber inglés?
      description: |
        Si la publicación no lo especifica, selecciona "Dunno" (aka "don't know")
      multiple: false
      options:
        - "Yes"
        - "No"
        - "Dunno"
    validations:
      required: false
  - type: dropdown
    id: active
    attributes:
      label: ¿El internship está recibiendo aplicaciones actualmente?
      multiple: false
      options:
        - "Yes"
        - "No"
    validations:
      required: false
  - type: checkboxes
    id: is_visible
    attributes:
      label: ¿Eliminar este Internship de la lista?
      description: Sólo selecciona esta casilla si el internship es *fake* (falso), no encaja con la temática del repositorio (ej. es de diseñador) o es ofensivo.
      options:
        - label: "Sí, eliminar este internship"
  - type: input
    id: email
    attributes:
      label: Email asociado a tu cuenta de GitHub (opcional)
      description: |
        Si quieres ser añadido como **Contributor** en el repositorio cuando el *github action* añada
        tu contribución al repositorio, por favor añade tu email. Sólo usaremos tu email para esto. Si 
        lo dejas en blanco, tu contribución será hecha de forma anónima por el bot actions@github.com.
      placeholder: ex. firstLast@gmail.com
    validations:
      required: false
  - type: textarea
    id: reason
    attributes:
      label: Razón para editar
      description: Si el motivo de tu edición no es obvio (e incluso si lo es), por favor explícala aquí.
      placeholder: This internship is no longer accepting applications...
    validations:
      required: false
      
